# Generated by Django 5.1.3 on 2024-12-18 02:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchcode', models.CharField(max_length=100)),
                ('branchname', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='InspectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('closed', 'Closed')], default='upcoming', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inspectionschedule',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspection.branch')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesmancode', models.CharField(max_length=50, unique=True)),
                ('salesmanname', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.branch')),
            ],
            options={
                'db_table': 'salesman',
            },
        ),
        migrations.CreateModel(
            name='DeviceInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('Tablet', 'Tablet'), ('Printer', 'Printer')], max_length=50)),
                ('sn', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('condition', models.CharField(choices=[('ปกติ', 'ปกติ'), ('ชำรุด', 'ชำรุด')], max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('inspected_at', models.DateTimeField(auto_now_add=True)),
                ('charger_status_tablet', models.CharField(choices=[('ปกติ', 'ปกติ'), ('ชำรุด', 'ชำรุด')], default='ปกติ', max_length=10, verbose_name='Tablet Charger Status')),
                ('charger_status_printer', models.CharField(choices=[('ปกติ', 'ปกติ'), ('ชำรุด', 'ชำรุด')], default='ปกติ', max_length=10, verbose_name='Printer Charger Status')),
                ('bag_status', models.CharField(blank=True, choices=[('ปกติ', 'ปกติ'), ('ชำรุด', 'ชำรุด')], default='ปกติ', max_length=10, null=True, verbose_name='Bag Status')),
                ('tablet_image', models.ImageField(blank=True, null=True, upload_to='uploads/tablet_images/')),
                ('charger_image_tablet', models.ImageField(blank=True, null=True, upload_to='uploads/charger_images/')),
                ('charger_image_printer', models.ImageField(blank=True, null=True, upload_to='uploads/charger_images/')),
                ('bag_image', models.ImageField(blank=True, null=True, upload_to='uploads/bag_images/')),
                ('printer_image', models.ImageField(blank=True, null=True, upload_to='uploads/printer_images/')),
                ('period', models.CharField(blank=True, max_length=7, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.branch')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='inspection.inspectionschedule')),
                ('salesman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspection.salesman')),
            ],
            options={
                'db_table': 'deviceinspection',
            },
        ),
    ]
