# Generated by Django 5.1.3 on 2024-12-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinspection',
            name='sn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='deviceinspection',
            constraint=models.UniqueConstraint(fields=('sn', 'period'), name='unique_sn_period'),
        ),
    ]
