# Generated by Django 5.1.3 on 2024-12-10 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saleman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salemancode', models.CharField(max_length=50, unique=True)),
                ('salemanname', models.CharField(max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.branch')),
            ],
        ),
        migrations.AddField(
            model_name='deviceinspection',
            name='saleman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspection.saleman'),
        ),
    ]
