# Generated by Django 5.1.3 on 2024-12-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinspection',
            name='image',
        ),
        migrations.AddField(
            model_name='deviceinspection',
            name='bag_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/bags/'),
        ),
        migrations.AddField(
            model_name='deviceinspection',
            name='bag_status',
            field=models.CharField(blank=True, choices=[('ปกติ', 'ปกติ'), ('ชำรุด', 'ชำรุด')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deviceinspection',
            name='charger_image_printer',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/chargers/printer/'),
        ),
        migrations.AddField(
            model_name='deviceinspection',
            name='charger_image_tablet',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/chargers/tablet/'),
        ),
        migrations.AddField(
            model_name='deviceinspection',
            name='charger_status_printer',
            field=models.CharField(blank=True, choices=[('ปกติ', 'ปกติ'), ('ชำรุด', 'ชำรุด')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deviceinspection',
            name='charger_status_tablet',
            field=models.CharField(blank=True, choices=[('ปกติ', 'ปกติ'), ('ชำรุด', 'ชำรุด')], max_length=10, null=True),
        ),
    ]
