# Generated by Django 5.1.3 on 2024-12-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_remove_deviceinspection_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinspection',
            name='printer_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/printer_images/'),
        ),
        migrations.AddField(
            model_name='deviceinspection',
            name='tablet_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tablet_images/'),
        ),
        migrations.AlterField(
            model_name='deviceinspection',
            name='bag_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/bag_images/'),
        ),
        migrations.AlterField(
            model_name='deviceinspection',
            name='bag_status',
            field=models.CharField(blank=True, choices=[('ปกติ', 'ปกติ'), ('ชำรุด', 'ชำรุด')], default='ปกติ', max_length=10, null=True, verbose_name='Bag Status'),
        ),
        migrations.AlterField(
            model_name='deviceinspection',
            name='charger_image_printer',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/charger_images/'),
        ),
        migrations.AlterField(
            model_name='deviceinspection',
            name='charger_image_tablet',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/charger_images/'),
        ),
        migrations.AlterField(
            model_name='deviceinspection',
            name='charger_status_printer',
            field=models.CharField(choices=[('ปกติ', 'ปกติ'), ('ชำรุด', 'ชำรุด')], default='ปกติ', max_length=10, verbose_name='Printer Charger Status'),
        ),
        migrations.AlterField(
            model_name='deviceinspection',
            name='charger_status_tablet',
            field=models.CharField(choices=[('ปกติ', 'ปกติ'), ('ชำรุด', 'ชำรุด')], default='ปกติ', max_length=10, verbose_name='Tablet Charger Status'),
        ),
    ]
