# Generated by Django 5.1.3 on 2024-12-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_saleman_deviceinspection_saleman'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinspection',
            name='sn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
