# Generated by Django 5.1.3 on 2024-12-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_deviceinspection_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleman',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
