# Generated by Django 5.1.3 on 2024-12-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0004_saleman_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinspection',
            name='sn',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
